spring:
  sql:
    init:
      mode: never

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: elamanabjalov824@gmail.com
    password: phvysxlyfbezhdie    # App password от Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

  mvc:
    contentnegotiation:
      favor-path-extension: false
      favor-parameter: false
      ignore-accept-header: true
      default-content-type: application/json

app:
  security:
    jwt:
      secret_key: super_secret_key_123
      expiration: 86400000

server:
  port: 8081
  error:
    include-message: always

---

spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/demo111
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:demo111;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
