spring:
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/demo111
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: elamanabjalov824@gmail.com
    password: phvysxlyfbezhdie  # App password от Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

  mvc:
    contentnegotiation:
      favor-path-extension: false
      favor-parameter: false
      ignore-accept-header: true
      default-content-type: application/json

server:
  port: 8081
  error:
    include-message: always

app:
  security:
    jwt:
      secret_key: super_secret_key_123
      expiration: 86400000
